### ISSUE TITLE
venachain-cdt   多文件项目  编译WASM文件

### ISSUE THREAD

**Issue by alanmoleapfive** [Venachain/Venachain#10]
alan@debian:~/venachain/demo$ venachain-init -project=cmake_example
alan@debian:~/venachain/demo$ ls
cmake_example  example
alan@debian:~/venachain/demo$ cd cmake_example
alan@debian:~/venachain/demo/cmake_example$ ls
build  CMakeLists.txt  include  README.txt  src
alan@debian:~/venachain/demo/cmake_example$ cd build
alan@debian:~/venachain/demo/cmake_example/build$ cmake ..
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting up Venachain Wasm Toolchain 0.1.9 at /usr/local/venachain.cdt
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.22)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/alan/venachain/demo/cmake_example/build
alan@debian:~/venachain/demo/cmake_example/build$ make 
[ 11%] Creating directories for 'cmake_example_project'
[ 22%] No download step for 'cmake_example_project'
[ 33%] No update step for 'cmake_example_project'
[ 44%] No patch step for 'cmake_example_project'
[ 55%] Performing configure step for 'cmake_example_project'
-- Setting up Venachain Wasm Toolchain 0.1.9 at /usr/local/venachain.cdt
-- Setting up Venachain Wasm Toolchain 0.1.9 at /usr/local/venachain.cdt
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Setting up Venachain Wasm Toolchain 0.1.9 at /usr/local/venachain.cdt
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.22)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/alan/venachain/demo/cmake_example/build/cmake_example
[ 66%] Performing build step for 'cmake_example_project'
Scanning dependencies of target cmake_example
[ 50%] Building CXX object CMakeFiles/cmake_example.dir/cmake_example.obj
[100%] Linking CXX executable cmake_example.wasm
[100%] Built target cmake_example
[ 77%] No install step for 'cmake_example_project'
[ 88%] No test step for 'cmake_example_project'
[100%] Completed 'cmake_example_project'
[100%] Built target cmake_example_project

**Comment by icechen128** [comment]
我这里没有复现出你的问题。可否提供一下使用的`cmake`版本，项目工程等信息。

另外，可以尝试在`CMakeLists.txt`开头加上

```
cmake_minimum_required(VERSION 3.0)
```

**Comment by alanmoleapfive** [comment]
cmake --version
cmake version 3.22.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by icechen128** [comment]
可以查看`build/cmake_example/`下有没有编译好的 wasm 和 abi 文件(类似于`cmake_example.wasm`和`cmake_example.abi.json`)，再使用vcl进行部署调用测试。

如果没有编译好的文件，可以查看`build/CMakeFiles`下有没有`CMakeError.log`和`CMakeOutput.log`，通过更详细的日志来定位可能出现的编译/链接问题。
