### ISSUE TITLE
remix   通过  injected provider web3  进行合约部署时出错

### ISSUE THREAD

**Issue by alanmoleapfive** [Venachain/Venachain#11]
creation of HelloWorld errored: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"invalid sender"}}}'

**Comment by eternalW** [comment]
麻烦确认一下metamask链接的本地链节点是否是venachain节点

**Comment by alanmoleapfive** [comment]
metamask连接的不是本地节点，是远程节点，能连接登录进去，合约部署就不行
连接的是venachain节点

**Comment by wxzhangwei** [comment]
确认，metamsk签名账户和合约部署的账户是否一致

**Comment by wxzhangwei** [comment]
烦请确认下metamask网络设置的chainid是否是300
