### ISSUE TITLE
Fatal: to do: send Transaction through http error: rlp: too few elements for types.txdata

### ISSUE THREAD

**Issue by alanmoleapfive** [Venachain/Venachain#12]
vcl contract deploy "example.wasm" --abi "example.cpp.abi.json" --keyfile /home/venachain/conf/keyfile.json
Passphrase: 
Fatal: to do: send Transaction through http error: rlp: too few elements for types.txdata

venachain 节点参数
result: {"code":0,"msg":"success","data":[{"name":"0","owner":"0xa9f35f58e206edb75410c5a94e35408ea5d69437","desc":"","type":1,"status":1,"externalIP":"192.168.1.47","internalIP":"192.168.1.47","publicKey":"2ec537195f1119df7c58cc9c4f147ae8e65f83c2e9951091af88f29ce271525be848c6763f0f69722c8954eec11aeb2abf430c3808160635781f4db788ab138b","rpcPort":6794,"p2pPort":16794},{"name":"1","owner":"0x","desc":"","type":1,"status":1,"externalIP":"192.168.1.48","internalIP":"192.168.1.48","publicKey":"212b638890a84dba1816ab169869f895c791cdf10538d12f4d4811f5a70bd0434f134f32d4973092de4f039f1e368ec435becfd3609ec16637d8c4d9b29fcd68","rpcPort":6794,"p2pPort":16794},{"name":"2","owner":"0x","desc":"","type":1,"status":1,"externalIP":"192.168.1.49","internalIP":"192.168.1.49","publicKey":"6f9c7822561fb78e4a0999e4597c9e8e61929a0fe1589b74ce1cef7fdc531761aad194ce31f0f21043d0c21b97528e08d2e18c2186bfddf90135ef9dbac2713d","rpcPort":6794,"p2pPort":16794}]}

**Comment by alanmoleapfive** [comment]
vcl contract deploy "example.wasm" --abi "example.cpp.abi.json" --keyfile /home/venachain/conf/keyfile.json --url 192.168.1.47:6794
Passphrase: 
result:
0xf0c5ce536e8bed17f87c0d2f03b28aa488cd5e6bbc1c3b86658a152bec0f41b7

{"jsonrpc":"2.0","method":"txpool_status","params":[],"id":67}
{
    "jsonrpc": "2.0",
    "id": 67,
    "result": {
        "pending": "0x1",
        "queued": "0x0"
    }
}

**Comment by alanmoleapfive** [comment]
节点信息
result: {"code":0,"msg":"success","data":[{"name":"0","owner":"0xa9f35f58e206edb75410c5a94e35408ea5d69437","desc":"","type":1,"status":1,"externalIP":"192.168.1.47","internalIP":"192.168.1.47","publicKey":"2ec537195f1119df7c58cc9c4f147ae8e65f83c2e9951091af88f29ce271525be848c6763f0f69722c8954eec11aeb2abf430c3808160635781f4db788ab138b","rpcPort":6794,"p2pPort":16794},{"name":"1","owner":"0x","desc":"","type":1,"status":1,"externalIP":"192.168.1.48","internalIP":"192.168.1.48","publicKey":"212b638890a84dba1816ab169869f895c791cdf10538d12f4d4811f5a70bd0434f134f32d4973092de4f039f1e368ec435becfd3609ec16637d8c4d9b29fcd68","rpcPort":6794,"p2pPort":16794},{"name":"2","owner":"0x","desc":"","type":1,"status":1,"externalIP":"192.168.1.49","internalIP":"192.168.1.49","publicKey":"6f9c7822561fb78e4a0999e4597c9e8e61929a0fe1589b74ce1cef7fdc531761aad194ce31f0f21043d0c21b97528e08d2e18c2186bfddf90135ef9dbac2713d","rpcPort":6794,"p2pPort":16794}]}

**Comment by wxccui** [comment]
> vcl contract deploy "example.wasm" --abi "example.cpp.abi.json" --keyfile /home/venachain/conf/keyfile.json Passphrase: Fatal: to do: send Transaction through http error: rlp: too few elements for types.txdata
> 
> venachain 节点参数 result: {"code":0,"msg":"success","data":[{"name":"0","owner":"0xa9f35f58e206edb75410c5a94e35408ea5d69437","desc":"","type":1,"status":1,"externalIP":"192.168.1.47","internalIP":"192.168.1.47","publicKey":"2ec537195f1119df7c58cc9c4f147ae8e65f83c2e9951091af88f29ce271525be848c6763f0f69722c8954eec11aeb2abf430c3808160635781f4db788ab138b","rpcPort":6794,"p2pPort":16794},{"name":"1","owner":"0x","desc":"","type":1,"status":1,"externalIP":"192.168.1.48","internalIP":"192.168.1.48","publicKey":"212b638890a84dba1816ab169869f895c791cdf10538d12f4d4811f5a70bd0434f134f32d4973092de4f039f1e368ec435becfd3609ec16637d8c4d9b29fcd68","rpcPort":6794,"p2pPort":16794},{"name":"2","owner":"0x","desc":"","type":1,"status":1,"externalIP":"192.168.1.49","internalIP":"192.168.1.49","publicKey":"6f9c7822561fb78e4a0999e4597c9e8e61929a0fe1589b74ce1cef7fdc531761aad194ce31f0f21043d0c21b97528e08d2e18c2186bfddf90135ef9dbac2713d","rpcPort":6794,"p2pPort":16794}]}

`vcl contract deploy` 在不指定 url 参数时，默认的 url 为`http://127.0.0.1:6791`，请确认一下交易发向的地址是否是 Venachain 的节点地址。

**Comment by wxccui** [comment]
> vcl contract deploy "example.wasm" --abi "example.cpp.abi.json" --keyfile /home/venachain/conf/keyfile.json --url 192.168.1.47:6794 Passphrase: result: 0xf0c5ce536e8bed17f87c0d2f03b28aa488cd5e6bbc1c3b86658a152bec0f41b7
> 
> {"jsonrpc":"2.0","method":"txpool_status","params":[],"id":67} { "jsonrpc": "2.0", "id": 67, "result": { "pending": "0x1", "queued": "0x0" } }

能否提供一下 Venachain的版本，版本可以在 `Venachain/release/linux/scripts/` 目录下运行 
```venachainctl.sh version```

**Comment by alanmoleapfive** [comment]
./venachainctl.sh version
venachain version 1.0.1-stable-ad1e1dc0

三个共识节点，有一个共识节点外网没有开通，导致出块很慢，
0x1821adbfba5
0x1821bd999ec
这是两个块之间的时间戳

**Comment by alanmoleapfive** [comment]
我把防火墙关闭了，三个共识节点都工作正常，但是部署合约出块很慢，都好几分钟了

**Comment by wxccui** [comment]
> 我把防火墙关闭了，三个共识节点都工作正常，但是部署合约出块很慢，都好几分钟了 { "jsonrpc": "2.0", "id": 67, "result": { "pending": { "0xa9f35f58e206EDb75410C5a94e35408eA5D69437": { "11471763542023385325": "contract creation: 0 wei + 0 gas × 0 wei" } }, "queued": {} } }

这几个共识节点之间可以互通吗，共识算法要正常工作这点是必须的。可以先试一下节点之间能不能 ping 通

**Comment by alanmoleapfive** [comment]
能ping能

**Comment by wxccui** [comment]
确认下连接的是否是Venachain节点，chainid是否是300
