### ISSUE TITLE
vcl contract deploy "example.wasm" --abi "example.cpp.abi.json" --keyfile 

### ISSUE THREAD

**Issue by alanmoleapfive** [Venachain/Venachain#13]
vcl contract deploy "example.wasm" --abi "example.cpp.abi.json" --keyfile /home/venachain/conf/keyfile.json --url 192.168.1.47:6794
Passphrase: 
result:
0x7f60b51a9ebae9b79a654a8f9258a3f8b690f1d0faeae49fa8812b696c893c9a
[root@orderer example]# vcl contract receipt 0x7f60b51a9ebae9b79a654a8f9258a3f8b690f1d0faeae49fa8812b696c893c9a
the tx receipt is not generated, please try again later
result:
null
[root@orderer example]# vcl contract receipt 0x7f60b51a9ebae9b79a654a8f9258a3f8b690f1d0faeae49fa8812b696c893c9a
the tx receipt is not generated, please try again later
result:
null

返回数据不对

**Comment by DE-PART** [comment]
在一定的时间内没有拿到交易的回执，会返回交易的hash，可以等一段时间后使用该hash查询receipt
