### ISSUE TITLE
部署单节点时无法生成account

### ISSUE THREAD

**Issue by zzqAlex** [Venachain/Venachain#16]
你好，我在部署单节点时，遇到无法生成account的问题，请帮忙指点下具体啥问题
环境：Ubuntu18.04
gcc：7.5.0
cmake：3.10.2
golang：1.11.12

linux/conf/下没有生成keyfile.json
linux/data/node-0/logs/venachain_error.log里面没有内容
错误如下：
![image](https://user-images.githubusercontent.com/44628575/203310182-dad78c3c-b141-49a9-91e1-4aaefb7bc5fe.png)

**Comment by zzqAlex** [comment]
linux/data/node-0/logs/venachain_log下的日志内容如下：

INFO [11-22|19:22:33.151|cmd/utils/flags.go:882] Maximum peer count                       ETH=50 LES=0 total=50 RoutineID=1
INFO [11-22|19:22:33.161|node/node.go:167]       Starting peer-to-peer node               instance=Venachain/venachain/v1.1.2-stable-c43efa31/linux-amd64/go1.16.13 RoutineID=1
INFO [11-22|19:22:33.161|venadb/database.go:15]  new database                             dbtype=leveldb RoutineID=1
INFO [11-22|19:22:33.162|venadb/leveldb/leveldb.go:73] Allocated cache and file handles         database=/mnt/d/Ubuntu18.04/venachain_test/linux/data/node-0/venachain/extdb cache=768 handles=512 RoutineID=1
INFO [11-22|19:22:33.197|venadb/database.go:15]        new database                             dbtype=leveldb RoutineID=1
INFO [11-22|19:22:33.201|venadb/leveldb/leveldb.go:73] Allocated cache and file handles         database=/mnt/d/Ubuntu18.04/venachain_test/linux/data/node-0/venachain/chaindata cache=768 handles=512 RoutineID=1
INFO [11-22|19:22:33.239|core/genesis.go:177]          Chain already have been initialized.     RoutineID=1
INFO [11-22|19:22:33.241|vena/backend.go:154]          Initialised chain configuration          config="{ChainID: 300 Engine: istanbul}" RoutineID=1
INFO [11-22|19:22:33.241|vena/backend.go:174]          Initialising Ethereum protocol           versions=[1] network=1 RoutineID=1
INFO [11-22|19:22:33.244|core/blockchain.go:264]       Loaded most recent local header          number=0 hash=17e807…c77e62 age=53y7mo1w RoutineID=1
INFO [11-22|19:22:33.244|core/blockchain.go:265]       Loaded most recent local full block      number=0 hash=17e807…c77e62 age=53y7mo1w RoutineID=1
INFO [11-22|19:22:33.244|core/blockchain.go:266]       Loaded most recent local fast block      number=0 hash=17e807…c77e62 age=53y7mo1w RoutineID=1
INFO [11-22|19:22:33.249|core/tx_journal.go:166]       Regenerated local transaction journal    transactions=0 accounts=0 RoutineID=1
INFO [11-22|19:22:33.249|miner/worker.go:237]          commitDuration in Millisecond            commitDuration=2850 RoutineID=1
INFO [11-22|19:22:33.249|p2p/server.go:604]            Starting P2P networking                  RoutineID=1
INFO [11-22|19:22:33.250|p2p/server.go:988]            RLPx listener up                         self="enode://fc686583b1a0e41ffc46c4d6f48e1d196400339714b8078202ab9f099d16bebdb330f78dd3fd33aeadb6f77ce4ec494ae610de892213375d0633397db19792b8@[::]:16791?discport=0" RoutineID=94
INFO [11-22|19:22:33.250|p2p/server.go:803]            ********** current peers length ********** len=0 RoutineID=96
INFO [11-22|19:22:33.251|p2p/server.go:803]            ********** current peers length ********** len=0 RoutineID=96
WARN [11-22|19:22:33.251|p2p/dial.go:200]              Removing static dial candidate           id=fc686583b1a0e41f addr=127.0.0.1:16791 err="is self" RoutineID=96
INFO [11-22|19:22:33.251|core/tx_pool.go:620]          Get pending txs                          duration=6.96µs txCnt=0 RoutineID=87
INFO [11-22|19:22:33.251|vena/backend.go:500]          the miner was not running, initialize it RoutineID=1
INFO [11-22|19:22:33.252|core/tx_pool.go:534]          Transaction pool price threshold updated price=1000000000 RoutineID=1
INFO [11-22|19:22:33.252|consensus/iris/core/core.go:381] ================================================== RoutineID=136
INFO [11-22|19:22:33.255|consensus/iris/core/core.go:383] New round Height: 1	Round: 0	Proposer: 0xD86DbB9C7CCD6728eF9A40B7e2c833e6ddA1fa88	IsProposer: true address=0xD86DbB9C7CCD6728eF9A40B7e2c833e6ddA1fa88 old_round=-1 old_seq=0 old_proposer=0xD86DbB9C7CCD6728eF9A40B7e2c833e6ddA1fa88 valSet=[0xD86DbB9C7CCD6728eF9A40B7e2c833e6ddA1fa88] size=1 RoutineID=136
INFO [11-22|19:22:33.253|core/tx_pool.go:620]             Get pending txs                          duration=1.267µs txCnt=0 RoutineID=87
ERROR[11-22|19:22:33.253|node/node.go:320]                listen unix /mnt/d/Ubuntu18.04/venachain_test/linux/data/node-0/node-0.ipc: bind: operation not supported RoutineID=1
INFO [11-22|19:22:33.255|core/blockchain.go:701]          Blockchain manager stopped               RoutineID=1
INFO [11-22|19:22:33.256|vena/handler.go:256]             Stopping Ethereum protocol               RoutineID=1
INFO [11-22|19:22:33.256|vena/handler.go:277]             Ethereum protocol stopped                RoutineID=1
INFO [11-22|19:22:33.256|core/tx_pool.go:508]             Transaction pool stopped                 RoutineID=1

**Comment by eternalW** [comment]
ERROR[11-22|19:22:33.253|node/node.go:320] listen unix /mnt/d/Ubuntu18.04/venachain_test/linux/data/node-0/node-0.ipc: bind: operation not supported RoutineID=1
节点没有正常启动,监听的ipc接口也就是6791接口失败，导致节点启动失败

**Comment by eternalW** [comment]
可能原因：
 1. 接口已被占用
 2. /mnt/d/Ubuntu18.04/venachain_test/linux/data/node-0/node-0.ipc 该路劲无法创建socket接口，可以尝试把项目换个文件路劲，放到~/下

**Comment by zzqAlex** [comment]
问题已解决，多谢
