### ISSUE TITLE
undefined: precompile.Asset

### ISSUE THREAD

**Issue by alanmoleapfive** [Venachain/Venachain#9]
make clean && make all

# github.com/Venachain/Venachain/cmd/vcl/client/packet
cmd/vcl/client/packet/tx_receipt.go:140:29: undefined: precompile.Asset
cmd/vcl/client/packet/tx_receipt_deprecated.go:19:29: undefined: precompile.Asset
github.com/Venachain/Venachain/cmd/vcl/common
# github.com/Venachain/Venachain/cmd/vcl/common
cmd/vcl/common/common.go:45:36: undefined: precompile.Asset
github.com/Venachain/Venachain/cmd/vcl/test
github.com/Venachain/Venachain/cmd/venachain
github.com/Venachain/Venachain/cmd/venakey
github.com/Venachain/Venachain/cmd/wasm
github.com/Venachain/Venachain/perf_test
util.go:45: exit status 2
exit status 1
make: *** [Makefile:32: all] Error 1

**Comment by icechen128** [comment]
这是由于go版本对于`go get`的不同处理方式导致的。

go1.17版本后不再推荐使用`go get`安装可执行文件，暂时可以将`build/build_deps.sh`文件第77行

```
build/env.sh go get -u github.com/go-bindata/go-bindata/...
```

改为

```
build/env.sh go install -a -v github.com/go-bindata/go-bindata/...@latest
```

 再重新make来解决这个问题，我们会在下个版本发布中修复这个问题。

参考：[Deprecation of 'go get' for installing executables](https://docs.studygolang.com/doc/go-get-install-deprecation)
